# Generated by Django 6.0.8 on 2026-08-29 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radius_sync', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NasDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Debe coincidir con el shortname en clients.conf', max_length=100)),
                ('ip_address', models.GenericIPAddressField(help_text='IP real del NAS, o de su túnel VPN si aplica')),
                ('model', models.CharField(blank=True, max_length=100)),
                ('environment', models.CharField(choices=[('lab', 'Laboratorio'), ('production', 'Producción')], default='lab', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['environment', 'name'],
            },
        ),
        migrations.AddField(
            model_name='radiussynclog',
            name='attempt',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
