# Generated by Django 6.0.8 on 2026-08-29 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radius_sync', '0002_nasdevice_radiussynclog_attempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='nasdevice',
            name='connection_type',
            field=models.CharField(choices=[('direct', 'IP pública directa'), ('wireguard', 'Túnel WireGuard')], default='wireguard', max_length=20),
        ),
        migrations.AddField(
            model_name='nasdevice',
            name='wireguard_public_key',
            field=models.CharField(blank=True, help_text='Public key del peer en wg-easy — solo informativo, la config real vive en el hub WireGuard.', max_length=64),
        ),
        migrations.AlterField(
            model_name='nasdevice',
            name='ip_address',
            field=models.GenericIPAddressField(help_text='IP que FreeRADIUS realmente ve en clients.conf: la del túnel WireGuard si connection_type=wireguard, o la pública si es conexión directa.'),
        ),
    ]
