# Generated by Django 6.0.8 on 2026-08-25 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_type', models.CharField(choices=[('onu', 'ONU'), ('router', 'Router CPE'), ('antenna', 'Antena')], max_length=20)),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('mac_address', models.CharField(blank=True, max_length=17)),
                ('status', models.CharField(default='in_stock', max_length=20)),
                ('assigned_date', models.DateField(blank=True, null=True)),
                ('assigned_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment', to='clients.client')),
            ],
        ),
    ]
