# Generated by Django 5.0.14 on 2026-08-29 05:08

import apps.portal.views
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('rut', models.CharField(help_text='Formato: 12345678-9 (sin puntos)', max_length=12, unique=True, verbose_name='RUT')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portal_user', to='clients.client', verbose_name='Cliente asociado')),
            ],
            options={
                'verbose_name': 'Usuario del portal',
                'verbose_name_plural': 'Usuarios del portal',
            },
        ),
        migrations.CreateModel(
            name='PortalToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default=apps.portal.views.generate_portal_token, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth_token', to='portal.clientuser')),
            ],
        ),
    ]
