# Generated by Django 6.0.8 on 2026-08-25 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('suspended', 'Suspendido por mora'), ('cancelled', 'Dado de baja'), ('pending', 'Pendiente instalación')], default='pending', max_length=20)),
                ('installation_date', models.DateField(blank=True, null=True)),
                ('billing_day', models.PositiveSmallIntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('download_speed', models.PositiveIntegerField(help_text='Mbps')),
                ('upload_speed', models.PositiveIntegerField(help_text='Mbps')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('burst_limit', models.CharField(blank=True, max_length=100)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pppoe_username', models.CharField(max_length=100, unique=True)),
                ('pppoe_password', models.CharField(max_length=100)),
                ('nas_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credential', to='clients.client')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clients.plan'),
        ),
    ]
